### ISSUE TITLE
Question: Is there a way to inherit StoryPage class from a custom Page model?

### ISSUE THREAD

**Issue by drimacus182** [torchbox/wagtail-webstories#4]
In my project I have a custom `BasePage` model subclassed from the `Page` class. It is the model every page on site must inherit. I'm trying to define a `StoryPage` class to be a `BaseWebStoryPage` and `BasePage` simultaneously. If I subclass a `StoryPage` from those two, I'll get problems with multiple inheritance. As far as I understand, there is no way to have a model, that is subclassed from the Page twice. 

So is there a way to define `StoryPage` class to inherit it from custom Page model?

**Comment by gasman** [comment]
Not currently - looks like it shouldn't be too hard to refactor BaseWebStoryPage to be available as a mixin class though.

**Comment by drimacus182** [comment]
@gasman Many thanks to you for implementing this feature
