### ISSUE TITLE
Migrations folder is not being included in PyPI

### ISSUE THREAD

**Issue by giuseppecardenas** [torchbox/wagtail-webstories#7]
When installing the package via pip I am getting a migration error because the migrations folder is not in the local package directory. Opening the .tar.gz in PyPI I can see that the migrations folder is not there. In the github repo the migrations folder is there. Please check and update the PyPI package.

**Comment by gasman** [comment]
Thanks for reporting! Have now released 0.0.4 with the packaging fixed.
