### ISSUE TITLE
url_hash field in ExternalStory model is too short

### ISSUE THREAD

**Issue by giuseppecardenas** [torchbox/wagtail-webstories#8]
For example, for this webstory: 

https://www-pcgamesn-com.cdn.ampproject.org/c/s/www.pcgamesn.com/amp-stories/best-battle-royale-games.html

The value returned by hexdigest is "8e3616b35b2f4d30f7dae987e23468ded00858c1", which has more than 32 characters so it produces an

(1406, "Data too long for column 'url_hash' at row 1")

error when publishing in wagtail.

I believe the author of the code had MD5 in mind, which does return a 32 character length hexdigest but it is instead using sha1, so I suggest changing to MD5 in the get_for_url method in the ExternalStory model, or increasing max character length for url_hash to 40.

**Comment by gasman** [comment]
Thanks for the report!
